package gregtech.loaders.preload;

import gregtech.api.enums.ItemList;
import gregtech.api.materials.Materials;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.objects.ItemData;
import gregtech.api.objects.MaterialStack;
import gregtech.api.util.GT_Log;
import gregtech.api.util.GT_ModHandler;
import gregtech.api.util.GT_OreDictUnificator;
import gregtech.api.util.GT_Utility;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.OreDictionary;

import static gregtech.api.enums.GT_Values.MATERIAL_UNIT;
import static gregtech.api.enums.GT_Values.MOD_ID_AE;
import static gregtech.api.enums.GT_Values.MOD_ID_FR;
import static gregtech.api.enums.GT_Values.MOD_ID_RC;
import static gregtech.api.enums.GT_Values.MOD_ID_TC;
import static gregtech.api.enums.GT_Values.MOD_ID_TF;

public class GT_Loader_ItemData
        implements Runnable {
    public void run() {
        GT_Log.out.println("GT_Mod: Loading Item Data Tags");
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_TF, "item.giantPick", 1L, 0), new ItemData(Materials.get("Stone"), 696729600L, new MaterialStack(Materials.get("Wood"), 464486400L)));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_TF, "item.giantSword", 1L, 0), new ItemData(Materials.get("Stone"), 464486400L, new MaterialStack(Materials.get("Wood"), 232243200L)));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_TF, "tile.GiantLog", 1L, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), 232243200L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_TF, "tile.GiantCobble", 1L, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Stone"), 232243200L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_TF, "tile.GiantObsidian", 1L, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Obsidian"), 232243200L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_TF, "item.minotaurAxe", 1L, 0), new ItemData(Materials.get("Diamond"), 14515200L, new MaterialStack(Materials.get("Wood"), OrePrefixes.stick.mMaterialAmount * 2L)));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_TF, "item.armorShards", 1L, 0), new ItemData(Materials.get("Knightmetal"), 403200L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_TF, "item.shardCluster", 1L, 0), new ItemData(Materials.get("Knightmetal"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(ItemList.TF_LiveRoot.get(1L), new ItemData(Materials.get("LiveRoot"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_AE, "item.ItemMultiMaterial", 1L, 10), new ItemData(Materials.get("CertusQuartz"), 1814400L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_AE, "item.ItemMultiMaterial", 1L, 11), new ItemData(Materials.get("NetherQuartz"), 1814400L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_AE, "item.ItemMultiMaterial", 1L, 12), new ItemData(Materials.get("Fluix"), 1814400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.quartz_block, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("NetherQuartz"), 14515200L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_AE, "tile.BlockQuartz", 1L, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("CertusQuartz"), 14515200L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_AE, "tile.BlockQuartzPillar", 1L, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("CertusQuartz"), 14515200L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_AE, "tile.BlockQuartzChiseled", 1L, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("CertusQuartz"), 14515200L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.wheat, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wheat"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.hay_block, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wheat"), 32659200L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.snowball, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Snow"), 907200L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.snow, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Snow"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.glowstone, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Glowstone"), 14515200L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.redstone_lamp, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Glowstone"), 14515200L, new MaterialStack(Materials.get("Redstone"), OrePrefixes.dust.mMaterialAmount * 4L)));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.lit_redstone_lamp, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Glowstone"), 14515200L, new MaterialStack(Materials.get("Redstone"), OrePrefixes.dust.mMaterialAmount * 4L)));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_FR, "craftingMaterial", 1L, 5), new ItemData(Materials.get("Ice"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.ice, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Ice"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.packed_ice, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Ice"), 7257600L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.clay_ball, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Clay"), 1814400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.clay, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Clay"), 7257600L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.hardened_clay, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Clay"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stained_hardened_clay, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Clay"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.brick_block, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Clay"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getIC2Item("Uran238", 1L), new ItemData(Materials.get("Uranium"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getIC2Item("Uran235", 1L), new ItemData(Materials.get("Uranium235"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getIC2Item("Plutonium", 1L), new ItemData(Materials.get("Plutonium"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getIC2Item("smallUran235", 1L), new ItemData(Materials.get("Uranium235"), 403200L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getIC2Item("smallPlutonium", 1L), new ItemData(Materials.get("Plutonium"), 403200L));
        GT_OreDictUnificator.addItemData(ItemList.IC2_Item_Casing_Iron.get(1L), new ItemData(Materials.get("Iron"), 1814400L));
        GT_OreDictUnificator.addItemData(ItemList.IC2_Item_Casing_Gold.get(1L), new ItemData(Materials.get("Gold"), 1814400L));
        GT_OreDictUnificator.addItemData(ItemList.IC2_Item_Casing_Bronze.get(1L), new ItemData(Materials.get("Bronze"), 1814400L));
        GT_OreDictUnificator.addItemData(ItemList.IC2_Item_Casing_Copper.get(1L), new ItemData(Materials.get("Copper"), 1814400L));
        GT_OreDictUnificator.addItemData(ItemList.IC2_Item_Casing_Tin.get(1L), new ItemData(Materials.get("Tin"), 1814400L));
        GT_OreDictUnificator.addItemData(ItemList.IC2_Item_Casing_Lead.get(1L), new ItemData(Materials.get("Lead"), 1814400L));
        GT_OreDictUnificator.addItemData(ItemList.IC2_Item_Casing_Steel.get(1L), new ItemData(Materials.get("Steel"), 1814400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.book, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Paper"), 10886400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.written_book, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Paper"), 10886400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.writable_book, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Paper"), 10886400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.enchanted_book, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Paper"), 10886400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.golden_apple, 1, 1), new ItemData(Materials.get("Gold"), OrePrefixes.block.mMaterialAmount * 8L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.golden_apple, 1, 0), new ItemData(Materials.get("Gold"), OrePrefixes.ingot.mMaterialAmount * 8L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.golden_carrot, 1, 0), new ItemData(Materials.get("Gold"), OrePrefixes.nugget.mMaterialAmount * 8L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.speckled_melon, 1, 0), new ItemData(Materials.get("Gold"), OrePrefixes.nugget.mMaterialAmount * 8L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.minecart, 1), new ItemData(Materials.get("Iron"), 18144000L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.iron_door, 1), new ItemData(Materials.get("Iron"), 21772800L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.cauldron, 1), new ItemData(Materials.get("Iron"), 25401600L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.iron_bars, 8, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Iron"), 10886400L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getIC2Item("ironFurnace", 1L), new ItemData(Materials.get("Iron"), 18144000L));
        GT_OreDictUnificator.addItemData(ItemList.IC2_Food_Can_Empty.get(1L), new ItemData(Materials.get("Tin"), 1814400L));
        GT_OreDictUnificator.addItemData(ItemList.IC2_Fuel_Rod_Empty.get(1L), new ItemData(Materials.get("Iron"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(ItemList.IC2_Fuel_Can_Empty.get(1L), new ItemData(Materials.get("Tin"), 25401600L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.light_weighted_pressure_plate, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Gold"), 7257600L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.heavy_weighted_pressure_plate, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Iron"), 7257600L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_RC, "tile.railcraft.anvil", 1L, 0), new ItemData(Materials.get("Steel"), 108864000L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_RC, "tile.railcraft.anvil", 1L, 1), new ItemData(Materials.get("Steel"), 72576000L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_RC, "tile.railcraft.anvil", 1L, 2), new ItemData(Materials.get("Steel"), 36288000L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.anvil, 1, 0), new ItemData(Materials.get("Iron"), 108864000L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.anvil, 1, 1), new ItemData(Materials.get("Iron"), 72576000L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.anvil, 1, 2), new ItemData(Materials.get("Iron"), 36288000L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.hopper, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Iron"), 18144000L, new MaterialStack(Materials.get("Wood"), 29030400L)));
        GT_OreDictUnificator.addItemData(ItemList.Cell_Universal_Fluid.get(1L), new ItemData(Materials.get("Tin"), 7257600L, new MaterialStack(Materials.get("Glass"), 1360800L)));
        GT_OreDictUnificator.addItemData(ItemList.Cell_Empty.get(1L), new ItemData(Materials.get("Tin"), 7257600L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.tripwire_hook, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Iron"), OrePrefixes.ring.mMaterialAmount * 2L, new MaterialStack(Materials.get("Wood"), MATERIAL_UNIT)));
        GT_OreDictUnificator.addItemData(ItemList.Bottle_Empty.get(1L), new ItemData(Materials.get("Glass"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.potionitem, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Glass"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stained_glass, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Glass"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.glass, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Glass"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stained_glass_pane, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Glass"), 1360800L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.glass_pane, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Glass"), 1360800L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.clock, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Gold"), 14515200L, new MaterialStack(Materials.get("Redstone"), MATERIAL_UNIT)));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.compass, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Iron"), 14515200L, new MaterialStack(Materials.get("Redstone"), MATERIAL_UNIT)));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.iron_horse_armor, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Iron"), 29030400L, new MaterialStack(Materials.get("Leather"), 21772800L)));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.golden_horse_armor, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Gold"), 29030400L, new MaterialStack(Materials.get("Leather"), 21772800L)));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.diamond_horse_armor, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Diamond"), 29030400L, new MaterialStack(Materials.get("Leather"), 21772800L)));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.leather, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Leather"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.beacon, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("NetherStar"), MATERIAL_UNIT, new MaterialStack(Materials.get("Obsidian"), 10886400L), new MaterialStack(Materials.get("Glass"), 18144000L)));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.enchanting_table, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Diamond"), 7257600L, new MaterialStack(Materials.get("Obsidian"), 14515200L), new MaterialStack(Materials.get("Paper"), 10886400L)));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.ender_chest, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("EnderEye"), MATERIAL_UNIT, new MaterialStack(Materials.get("Obsidian"), 29030400L)));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.bookshelf, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Paper"), 32659200L, new MaterialStack(Materials.get("Wood"), 21772800L)));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.lever, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Stone"), MATERIAL_UNIT, new MaterialStack(Materials.get("Wood"), 1814400L)));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.ice, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Ice"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.packed_ice, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Ice"), 7257600L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.snow, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Snow"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.snowball, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Snow"), 907200L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.snow_layer, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Snow"), -1L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.sand, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Sand"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.sandstone, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Sand"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stone_slab, 1, 0), new ItemData(Materials.get("Stone"), 1814400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stone_slab, 1, 8), new ItemData(Materials.get("Stone"), 1814400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.double_stone_slab, 1, 0), new ItemData(Materials.get("Stone"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.double_stone_slab, 1, 8), new ItemData(Materials.get("Stone"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stone_slab, 1, 1), new ItemData(Materials.get("Sand"), 1814400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stone_slab, 1, 9), new ItemData(Materials.get("Sand"), 1814400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.double_stone_slab, 1, 1), new ItemData(Materials.get("Sand"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.double_stone_slab, 1, 9), new ItemData(Materials.get("Sand"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stone_slab, 1, 2), new ItemData(Materials.get("Wood"), 1814400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stone_slab, 1, 10), new ItemData(Materials.get("Wood"), 1814400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.double_stone_slab, 1, 2), new ItemData(Materials.get("Wood"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.double_stone_slab, 1, 10), new ItemData(Materials.get("Wood"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stone_slab, 1, 3), new ItemData(Materials.get("Stone"), 1814400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stone_slab, 1, 11), new ItemData(Materials.get("Stone"), 1814400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.double_stone_slab, 1, 3), new ItemData(Materials.get("Stone"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.double_stone_slab, 1, 11), new ItemData(Materials.get("Stone"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stone_slab, 1, 5), new ItemData(Materials.get("Stone"), 1814400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stone_slab, 1, 13), new ItemData(Materials.get("Stone"), 1814400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.double_stone_slab, 1, 5), new ItemData(Materials.get("Stone"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.double_stone_slab, 1, 13), new ItemData(Materials.get("Stone"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stone, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Stone"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.furnace, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Stone"), 29030400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.lit_furnace, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Stone"), 29030400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stonebrick, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Stone"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.cobblestone, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Stone"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.mossy_cobblestone, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Stone"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stone_button, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Stone"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.stone_pressure_plate, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Stone"), 7257600L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.ladder, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.wooden_button, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.wooden_pressure_plate, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), 7257600L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.fence, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), 5443200L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.bowl, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), MATERIAL_UNIT));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.sign, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), 7257600L));
        GT_OreDictUnificator.addItemData(new ItemStack(Items.wooden_door, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), 21772800L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.chest, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), 29030400L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.trapped_chest, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), 32659200L, new MaterialStack(Materials.get("Iron"), OrePrefixes.ring.mMaterialAmount * 2L)));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.unlit_redstone_torch, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), 1814400L, new MaterialStack(Materials.get("Redstone"), MATERIAL_UNIT)));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.redstone_torch, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), 1814400L, new MaterialStack(Materials.get("Redstone"), MATERIAL_UNIT)));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.noteblock, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), 29030400L, new MaterialStack(Materials.get("Redstone"), MATERIAL_UNIT)));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.jukebox, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), 29030400L, new MaterialStack(Materials.get("Diamond"), MATERIAL_UNIT)));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.crafting_table, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Wood"), 14515200L));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.piston, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Stone"), 14515200L, new MaterialStack(Materials.get("Wood"), 10886400L)));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.sticky_piston, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Stone"), 14515200L, new MaterialStack(Materials.get("Wood"), 10886400L)));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.dispenser, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Stone"), 25401600L, new MaterialStack(Materials.get("Redstone"), MATERIAL_UNIT)));
        GT_OreDictUnificator.addItemData(new ItemStack(Blocks.dropper, 1, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("Stone"), 25401600L, new MaterialStack(Materials.get("Redstone"), MATERIAL_UNIT)));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_TC, "ItemNuggetChicken", 1L, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("MeatCooked"), 403200L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_TC, "ItemNuggetBeef", 1L, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("MeatCooked"), 403200L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_TC, "ItemNuggetPork", 1L, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("MeatCooked"), 403200L));
        GT_OreDictUnificator.addItemData(GT_ModHandler.getModItem(MOD_ID_TC, "ItemNuggetFish", 1L, OreDictionary.WILDCARD_VALUE), new ItemData(Materials.get("MeatCooked"), 403200L));
        for (ItemStack tItem : new ItemStack[]{GT_ModHandler.getModItem(MOD_ID_TF, "item.meefRaw", 1L, 0), GT_ModHandler.getModItem(MOD_ID_TF, "item.venisonRaw", 1L, 0), new ItemStack(Items.porkchop), new ItemStack(Items.beef), new ItemStack(Items.chicken), new ItemStack(Items.fish)}) {
            if (tItem != null) {
                GT_OreDictUnificator.addItemData(GT_Utility.copyMetaData(OreDictionary.WILDCARD_VALUE, tItem), new ItemData(Materials.get("MeatRaw"), MATERIAL_UNIT, new MaterialStack(Materials.get("Bone"), 403200L)));
            }
        }
        for (ItemStack tItem : new ItemStack[]{GT_ModHandler.getModItem(MOD_ID_TF, "item.meefSteak", 1L, 0), GT_ModHandler.getModItem(MOD_ID_TF, "item.venisonCooked", 1L, 0), new ItemStack(Items.cooked_porkchop), new ItemStack(Items.cooked_beef), new ItemStack(Items.cooked_chicken), new ItemStack(Items.cooked_fished)}) {
            if (tItem != null) {
                GT_OreDictUnificator.addItemData(GT_Utility.copyMetaData(OreDictionary.WILDCARD_VALUE, tItem), new ItemData(Materials.get("MeatCooked"), MATERIAL_UNIT, new MaterialStack(Materials.get("Bone"), 403200L)));
            }
        }
    }
}
